name: Test and release when tagged

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          environments: lint
      - run: pixi run --environment lint lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - test-py312
          - test-py313
          - test-py314
    steps:
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          environments: ${{ matrix.environment }}
      - run: pixi run --environment ${{ matrix.environment }} test

  publish:
    needs: [test, lint]

    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/symbolite
    permissions:
      id-token: write  # for trusted publising to PyPI

    steps:
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          environments: build
      - name: Build the package
        run: pixi run --environment build _build
      - name: Publish to PyPI
        run: pixi run --environment build _publish
        if: github.ref_type == 'tag'
